name: Contract Tests

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      # Install node 
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install newman 
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  
             