name: Contract Tests

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      # Install node 
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install newman 
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  

      - name: Make directory for results
        run: mkdir -p ContractTestResults

      - name: Run postman 
        run: |
            newman run "RIG Partner - CI Migration.postman_collection (1).json" -e "RIG PARTNER DEV - CI.postman_environment.json"

      - name: Output
        uses: actions/upload-artifacts@v2
        with: 
          name: RunReports
          path: ContractTestResults  
             